_wandb:
    value:
        cli_version: 0.22.2
        e:
            ndxphk74deef7biq3m9s12z1c1lfgmhp:
                codePath: train_bert.py
                codePathLocal: train_bert.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "500101541888"
                        used: "43257921536"
                email: bunnyyadav04@gmail.com
                executable: C:\Users\karth\AppData\Local\Programs\Python\Python313\python.exe
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-45b4f3d6-7a9e-c90e-b08b-ced911832b0e
                host: Karthik
                memory:
                    total: "17041244160"
                os: Windows-11-10.0.26100-SP0
                program: D:\Finrapt\intent-classification using bert\train_bert.py
                python: CPython 3.13.7
                root: D:\Finrapt\intent-classification using bert
                startedAt: "2025-10-15T07:41:03.896136Z"
                writerId: ndxphk74deef7biq3m9s12z1c1lfgmhp
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
            "3":
                - 16
            "4": 3.13.7
            "5": 0.22.2
            "6": 4.57.1
            "8":
                - 3
            "12": 0.22.2
            "13": windows-amd64
batch_size:
    value: 8
epochs:
    value: 3
learning_rate:
    value: 5e-05
max_length:
    value: 64
model:
    value: bert-base-uncased
