_wandb:
    value:
        cli_version: 0.22.2
        e:
            piugwgp3csqy57dfid7zs0kp8u32kdnt:
                codePath: train_bert.py
                codePathLocal: train_bert.py
                email: bunnyyadav04@gmail.com
                executable: C:\Users\karth\AppData\Local\Programs\Python\Python313\python.exe
                host: Karthik
                os: Windows-11-10.0.26100-SP0
                program: D:\Finrapt\intent-classification using bert\train_bert.py
                python: CPython 3.13.7
                root: D:\Finrapt\intent-classification using bert
                startedAt: "2025-10-15T07:38:33.753693Z"
                writerId: piugwgp3csqy57dfid7zs0kp8u32kdnt
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
            "3":
                - 16
            "4": 3.13.7
            "5": 0.22.2
            "6": 4.57.1
            "8":
                - 3
            "12": 0.22.2
            "13": windows-amd64
batch_size:
    value: 8
epochs:
    value: 3
learning_rate:
    value: 5e-05
max_length:
    value: 64
model:
    value: bert-base-uncased
